include(CMakeFindDependencyMacro)
find_dependency(PddlParser)
find_dependency(Boost COMPONENTS system)
find_dependency(spdlog)
find_dependency(clips_vendor)
find_dependency(clips)
include("${CMAKE_CURRENT_LIST_DIR}/ClipsPddlParserTargets.cmake")
